# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend_infer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='backend_infer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13\x62\x61\x63kend_infer.proto\"A\n\nJobRequest\x12\x13\n\x0bsentence_id\x18\x01 \x01(\t\x12\n\n\x02sr\x18\x02 \x01(\t\x12\x12\n\nipa_id_seq\x18\x03 \x01(\t\"+\n\x08JobReply\x12\x0c\n\x04isOK\x18\x01 \x01(\x08\x12\x11\n\terror_msg\x18\x02 \x01(\t26\n\rbackend_infer\x12%\n\tcommitJob\x12\x0b.JobRequest\x1a\t.JobReply\"\x00\x62\x06proto3'
)




_JOBREQUEST = _descriptor.Descriptor(
  name='JobRequest',
  full_name='JobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence_id', full_name='JobRequest.sentence_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sr', full_name='JobRequest.sr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ipa_id_seq', full_name='JobRequest.ipa_id_seq', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=88,
)


_JOBREPLY = _descriptor.Descriptor(
  name='JobReply',
  full_name='JobReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isOK', full_name='JobReply.isOK', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='JobReply.error_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['JobRequest'] = _JOBREQUEST
DESCRIPTOR.message_types_by_name['JobReply'] = _JOBREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JobRequest = _reflection.GeneratedProtocolMessageType('JobRequest', (_message.Message,), {
  'DESCRIPTOR' : _JOBREQUEST,
  '__module__' : 'backend_infer_pb2'
  # @@protoc_insertion_point(class_scope:JobRequest)
  })
_sym_db.RegisterMessage(JobRequest)

JobReply = _reflection.GeneratedProtocolMessageType('JobReply', (_message.Message,), {
  'DESCRIPTOR' : _JOBREPLY,
  '__module__' : 'backend_infer_pb2'
  # @@protoc_insertion_point(class_scope:JobReply)
  })
_sym_db.RegisterMessage(JobReply)



_BACKEND_INFER = _descriptor.ServiceDescriptor(
  name='backend_infer',
  full_name='backend_infer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=135,
  serialized_end=189,
  methods=[
  _descriptor.MethodDescriptor(
    name='commitJob',
    full_name='backend_infer.commitJob',
    index=0,
    containing_service=None,
    input_type=_JOBREQUEST,
    output_type=_JOBREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BACKEND_INFER)

DESCRIPTOR.services_by_name['backend_infer'] = _BACKEND_INFER

# @@protoc_insertion_point(module_scope)
