// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: backend_infer.proto

#include "backend_infer.pb.h"
#include "backend_infer.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* backend_infer_method_names[] = {
  "/backend_infer/commitJob",
};

std::unique_ptr< backend_infer::Stub> backend_infer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< backend_infer::Stub> stub(new backend_infer::Stub(channel));
  return stub;
}

backend_infer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_commitJob_(backend_infer_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status backend_infer::Stub::commitJob(::grpc::ClientContext* context, const ::JobRequest& request, ::JobReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_commitJob_, context, request, response);
}

void backend_infer::Stub::experimental_async::commitJob(::grpc::ClientContext* context, const ::JobRequest* request, ::JobReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_commitJob_, context, request, response, std::move(f));
}

void backend_infer::Stub::experimental_async::commitJob(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::JobReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_commitJob_, context, request, response, std::move(f));
}

void backend_infer::Stub::experimental_async::commitJob(::grpc::ClientContext* context, const ::JobRequest* request, ::JobReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_commitJob_, context, request, response, reactor);
}

void backend_infer::Stub::experimental_async::commitJob(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::JobReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_commitJob_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::JobReply>* backend_infer::Stub::AsynccommitJobRaw(::grpc::ClientContext* context, const ::JobRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::JobReply>::Create(channel_.get(), cq, rpcmethod_commitJob_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::JobReply>* backend_infer::Stub::PrepareAsynccommitJobRaw(::grpc::ClientContext* context, const ::JobRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::JobReply>::Create(channel_.get(), cq, rpcmethod_commitJob_, context, request, false);
}

backend_infer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      backend_infer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< backend_infer::Service, ::JobRequest, ::JobReply>(
          std::mem_fn(&backend_infer::Service::commitJob), this)));
}

backend_infer::Service::~Service() {
}

::grpc::Status backend_infer::Service::commitJob(::grpc::ServerContext* context, const ::JobRequest* request, ::JobReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


